# Generated by Django 5.0.3 on 2024-04-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('picture', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': 'Player Data',
                'verbose_name_plural': 'Player Data',
            },
        ),
    ]
