# Generated by Django 5.0.3 on 2024-04-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('team_input', models.CharField(max_length=100, unique=True)),
                ('logo', models.CharField(max_length=255)),
            ],
        ),
    ]
