# Generated by Django 5.0.3 on 2024-04-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overunder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamdata',
            options={'verbose_name': 'Team Data', 'verbose_name_plural': 'Team Data'},
        ),
    ]
