# Generated by Django 5.0.3 on 2024-04-17 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overunder', '0002_alter_teamdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='abbreviation',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
